ZAAWANSOWANE JĘZYKI PROGRAMOWANIA
=================================

**rok akademicki 2018/2019, semestr zimowy**


LAB 01 [02.10.2018]
-------------------

**GitHub:**

* https://github.com/zjprog/2018
* rzucić okiem pobieżnie

**Labs:**

* https://exercism.io/[Exercism.io]
* zarejestrować się
* spróbować zacząć

**Cloc/Sloc, Flog, Flay...:**

* zintegrować z czymś
* pobawić się


LAB 02 [09.10.2018]
-------------------

1. Git / http://github.com[GitHub]
2. **Edytor:** Atom, VSC, Emacs, Vim (podłączyć linter<nie>
  wtyczkę pilnującą stylu, np. rubocop, ...)
3. Bash

4. repo do laboratorium + README.adoc
* ASCII Doctor
* tabelki

https://github.com/mre/awesome-static-analysis

**Java**

* Bash, Atom...
* cloc, flog, flay, rubocop...
* wtyczki...

* checkstyle	- checking Java source code for adherence to a Code
		            Standard or set of validation rules (best practices)

**WAŻNE!!!**

* coś do wyszukiwania duplikacji, podobieństw w kodzie źródłowym
* coś a'la flog; clean code...
* detektor code smell...
* coś w stylu RuboCop'a na Javę
* jakość, quality, critic...

ZROBIĆ REPO NA GITHUBIE, README.adoc, PRZYGOTOWAĆ ZARYS ŚRODOWISKA PRACY!


LAB 03 [16.10.2018]
-------------------

* ABC Complexity
* flog

------
---------|-----------------|---------|------->
       2000              2010      2018
------

**Zrobić:** obrazek z plikiem i wynikiem... brudny kod i ABC Complexity
coś jak tu: http://ruby.sadi.st/Flog.html[ruby.sadi.st/Flog.html]
lub na repo http://github.com/zjprog/2018[zjprog/2018] (GitHub). Ważne,
by uwzględnić punktację danej metryki (ABC) suma i podział (wprowadzić
do README.adoc albo innego, np. WTFCode.adoc).

**Pamiętać:** uzupełnić zbiór narzędzi potrzebnych do pracy na laboratoriach (!)


LAB 04 [23.10.2018]
-------------------

-----
   (1)           (2)           (3)
---------|-----------------|---------|------->
       2000              2010      2018
-----

**http://github.com/zjprog/2018[github.com/zjprog/2018]:**

**(1)** 1 - 4

**(2)** 5 - 7

**(3)** 8 - 12

**Zasady i wzorce:**

* SOLID
* DRY (Don't Repeat Yourself)
* LoD (the Law of Demeter)

**Forma zaliczenia:**

-> analog. "obrazek z plikiem i wynikiem..."

_"Dzisiaj pracujecie, a za tydzień sobie takie rzeczy pooglądamy"_
~ bardzo ważna informacja!


LAB 05 [30.10.2018]
-------------------

* Visual Studio Code
* Cobalt2
* Ligatury

**POPRAWIĆ PREZENTACJĘ WTF_CODE !!!**

Wszystko ma być widać na jednym ekranie:

-> kod źródłowy

-> efekt przepuszczenia przez narzędzie

-> każda linijka opisana (punktowo)

-> podział linijki na poszczególne punkty

**UWAGA:**

Kod powinien być konkretny, niezbyt długi i uzyskiwać wysoką notę (!).


LAB 06 [06.11.2018]
-------------------

Kata, Gilded Rose...

**GILDEDROSE:**

Sklonowany fragment repo do swojego repo, tylko fragment z Javą
(**o właśnie stąd:**
https://github.com/emilybache/GildedRose-Refactoring-Kata[GildedRose-Refactoring-Kata]).

**CO TERAZ?:** Ogarnąć to troszkę, obczaić co się dzieje... zrozumieć Kata
i spróbować  odpalić, testy mają przechodzić (!).

**ZALEGŁE(!):** poprawić WTFCode (przede wszystkim chodzi o sensowność kodu),
ew. w wolnej chwili poszukać lepszej metryki (ostateczność).


LAB 07 [13.11.2018]
-------------------

Zaduma nad if'ami...

Czym jest true w Java? Obiektem, typem prymitywnym, wartością boolowską?

-> https://docs.oracle.com/javase/tutorial/java/nutsandbolts/_keywords.html[_keywords.html]

**ANG:** _"true, false, and null might seem like keywords, but they are actually
literals; you cannot use them as identifiers in your programs."_

*PL:* _"true, false i null mogą wydawać się słowami kluczowymi, ale w
rzeczywistości są literałami; nie można ich używać jako identyfikatorów
w swoich programach."_

**CO TERAZ?:** Koniecznie zająć się GildedRose na spokojnie, jak ostatnio,

* zrozumieć, odpalić, testy mają przechodzić itp. (!!!)
* Teraz już naprawdę - wstępna teoria dziś na wykładzie!

-> "if by sending messages in java..."

**ZALEGŁE(!):** Raczej już nie będzie to sprawdzane, ale spróbować tego ABC z
Sonarem (http://qualilogy.com/en/the-abc-metric-2/[The ABC metric]) czy w ogóle
coś ruszy.


LAB 08 [20.11.2018]
-------------------

-----
stan początkowy :       kod działa        flog 98.9
propozycja zmiany :     new items
-----

**Avoiding _if_ Statements**

* https://dzone.com/articles/code-smells-if-statements[Code Smells - If Statements]
* https://www.quora.com/Why-should-Java-programmers-try-to-avoid-if-statements[Why should Java programmers try to avoid _if_ statements?]
* https://edgecoders.com/coding-tip-try-to-code-without-if-statements-d06799eed231[Coding tip - try to code without _if_ statements]
* http://ashtonkemerling.com/blog/2017/01/26/java-without-if/[Java without _if_]
* https://www.pluralsight.com/blog/it-ops/if-statements[_If_ statements: Do you really need them in your code?]
* and more...

**Some help with Kata**

-> https://github.com/modernSE/kata-refactoring-gilded-rose/blob/master/Java/src/main/java/com/gildedrose/GildedRose.java[ModernSE]

-> https://blog.sandra-parsick.de/2016/06/28/my-lesson-learned-from-doing-gilded-rose-kata/[My Lesson Learned From Doing Gilded Rose Kata]


LAB 09 [27.11.2018]
-------------------

Przykładowy raport na egzamin:

1. **Zadanie/testy:**   krótki opis [treść], wybrany język, testy... testy, które
                        nie przechodzą, "_dlaczego?_", "_co należy zrobić?_",
                        nowe testy, które przechodzą - super!

2. **Złożoność:**       przepuszczenie przez jakąś metrykę dla wizualizacji postępu,
                        że kod po zmianach faktycznie jest lepszy, prostszy, mniej
                        skomplikowany.

3. **Kod:**             przedstawienie struktury kodu, jakiegoś przykładu, struktura
                        nowych, świeżo dodawanych elementów.

4. **Refaktoryzacja:**  upraszczanie, "wieloplikowość" - nie mylić refaktoryzacji
                        z refaktoryzacją (!). Należy pokazać następujące etapy:
                            * **PRZED:**          przedstawienie w wersji oryginalnej
                            * **W MIĘDZYCZASIE:** przedstawienie procesu zmian
                            * **PO:**             przedstawienie w wersji poprawionej

Zadanie (na przykładzie Gilded Rose) polega na tym, aby przedstawić proces,
a nie samo rozwiązanie zadania.

Wysłać mail'a do prowadzącego zajęcia z nazwą grupy, składem i wybranym terminem
(jeden z trzech wykładów w styczniu - info https://github.com/zjprog/2018[zjprog/2018]).

* **Nazwa grupy:**      M.M. & M.P. Java
* **Skład:**            M.Mazepa, M.Pilkou
* **Termin:**           08.01.2019, godz. 12.15–13.45, a. 2


LAB 10 [04.12.2018]
-------------------

Co jest ważne w projekcie na egzamin?

* Zaprezentowanie procesu i konkretnych jego etapów zamiast gotowego
rozwiązania. Zmienność w czasie, zależność od jakichś metryk w kolejnych
etapach.

* Refaktoryzacja - ale nie sama w sobie, a trzymająca się pewnych reguł.
Opisać te reguły - z definicji i w odniesieniu do projektu.


LAB 11 [11.12.2018]
-------------------

Podczas Egzaminu (Prezentacji):

* **Na tablicy:**       Imiona i Nazwiska
* **Oceny:**            będą wystawione tego samego dnia
* **Czas prezentacji:** ok. 15 minut

Przez ostatnie trzy zajęcia:

* TRANSFORMACJE KODU (prawie refaktoryzacje;
  transformacje to prawie to samo co refaktoryzacje,
  tyle że refaktoryzacje dodatkowo polepszają strukturę)
