Zaawansowane języki programowania
---------------------------------

*Student:* Mariusz Mazepa

*Środowisko pracy*

[options="header"]
|===============================================================================================
| System operacyjny | Powłoka | Hostingowy serwis (Git) | Edytor | Obiektowy język programowania
| Linux Xubuntu     | Bash    | GitHub                  | Atom   | Java
|===============================================================================================

*Narzędzia dla języka Java*

[options="header"]
|==============================================================================================================================================================
| Narzędzie  | Link                               | Opis
| checkstyle | http://checkstyle.sourceforge.net/ | Checking Java source code for adherence to a Code Standard or set of validation rules (best practices).
| ckjm       | https://www.spinellis.gr/sw/ckjm/  | Calculates Chidamber and Kemerer object-oriented metrics by processing the bytecode of compiled Java files.
| Sonar      | https://www.sonarsource.com/       | SonarSource delivers what is probably the best static code analyzer you can find on the market for Java.
|==============================================================================================================================================================

Przydatne linki
---------------

* https://github.com/mre/awesome-static-analysis
* https://sonarcloud.io
* https://pmd.github.io/
* https://pl.wikipedia.org/wiki/Metryka_oprogramowania#Zestaw_metryk_CK

Testowanie metryk CKJM
----------------------

RFC.java

[source,java]
-----------------
import java.util.*;

public class RFC
{
  public static void main(String[] args)
  {
      ArrayDeque ad = new ArrayDeque();
      ArrayList al = new ArrayList();
      BitSet bs = new BitSet();
      HashMap hm = new HashMap();
      HashSet hs = new HashSet();
      Hashtable ht = new Hashtable();
      IdentityHashMap ihm = new IdentityHashMap();
      LinkedHashMap lhm = new LinkedHashMap();
      LinkedHashSet lhs = new LinkedHashSet();
      LinkedList ll = new LinkedList();
      String s = new String();
      Random r = new Random();
      RFC hw = new RFC();
      Stack st = new Stack();
      Timer t = new Timer();
      TreeMap tm = new TreeMap();
      TreeSet ts = new TreeSet();
      Vector v = new Vector();

      System.exit(0);
  }
}
-----------------

--------------------
RFC 2 1 0 0 21 1 0 2
--------------------

LCOM.java

[source,java]
-----------------
public class LCOM
{
  public static void method01() {};
  public static void method02() {};
  public static void method03() {};
  public static void method04() {};
  public static void method05() {};
  public static void method06() {};
  public static void method07() {};
  public static void method08() {};
  public static void method09() {};
  public static void method10() {};

  public static void main(String[] args)
  {

  }
}
-----------------

------------------------
LCOM 12 1 0 0 13 66 0 12
------------------------

*Podsumowanie*

[options="header"]
|===========================================================
| Plik       | WMC | DIT | NOC | CBO | RFC | LCOM | Ca | NPM
| RFC.class  | 2   | 1   | 0   | 0   | 21  | 1    | 0  | 2
| LCOM.class | 12  | 1   | 0   | 0   | 13  | 66   | 0  | 12
|===========================================================
